# Generated by Django 3.2 on 2022-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('genre', models.CharField(max_length=80)),
                ('review', models.IntegerField(null=True)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
    ]
